This is an internal working file generated by the Source Browser.
15:14 04s
C:\Documents and Settings\Administrator\桌面\光盘\物联网无线传感网络部分\exp\zigbee\点对点无线通信\source\apps\per_test\per_test.c
C:\Documents and Settings\Administrator\桌面\光盘\物联网无线传感网络部分\exp\zigbee\点对点无线通信\source\apps\per_test\per_test.c
-D
chip=2530
--diag_suppress
Pe001,Pa084
-o
C:\Documents and Settings\Administrator\桌面\光盘\物联网无线传感网络部分\exp\zigbee\点对点无线通信\ide\srf05_cc2530\iar\temp\per_test\
-e
--no_code_motion
--debug
--core=plain
--dptr=16,1
--data_model=large
--code_model=near
--calling_convention=xdata_reentrant
--place_constants=data
--nr_virtual_regs
8
-I
C:\Documents and Settings\Administrator\桌面\光盘\物联网无线传感网络部分\exp\zigbee\点对点无线通信\ide\srf05_cc2530\iar/../../../source/Components/utils\
-I
C:\Documents and Settings\Administrator\桌面\光盘\物联网无线传感网络部分\exp\zigbee\点对点无线通信\ide\srf05_cc2530\iar/../../../source/Components/common\
-I
C:\Documents and Settings\Administrator\桌面\光盘\物联网无线传感网络部分\exp\zigbee\点对点无线通信\ide\srf05_cc2530\iar/../../../source/Components/basicrf\
-I
C:\Documents and Settings\Administrator\桌面\光盘\物联网无线传感网络部分\exp\zigbee\点对点无线通信\ide\srf05_cc2530\iar/../../../source/Components/targets/interface\
-I
C:\Documents and Settings\Administrator\桌面\光盘\物联网无线传感网络部分\exp\zigbee\点对点无线通信\ide\srf05_cc2530\iar/../../../source/Components/assembly\
-I
C:\Documents and Settings\Administrator\桌面\光盘\物联网无线传感网络部分\exp\zigbee\点对点无线通信\ide\srf05_cc2530\iar/../../../source/Components/common/cc8051\
-I
C:\Documents and Settings\Administrator\桌面\光盘\物联网无线传感网络部分\exp\zigbee\点对点无线通信\ide\srf05_cc2530\iar/../../../source/Components/targets/srf05_soc\
-I
C:\Documents and Settings\Administrator\桌面\光盘\物联网无线传感网络部分\exp\zigbee\点对点无线通信\ide\srf05_cc2530\iar/../../../source/Components/radios/cc2530\
-I
C:\Program Files\IAR Systems\Embedded Workbench 5.3 Evaluation version\8051\INC\
-I
C:\Program Files\IAR Systems\Embedded Workbench 5.3 Evaluation version\8051\INC\CLIB\
-Ohz
